### ISSUE TITLE
Allow to specify filename in `path` 

### ISSUE THREAD

**Issue by JulienBlasco** [ddotta/tablexlsx#29]
Two suggestions:

- move the `path` argument in second position in arguments list (seems a better practice since path is the other mandatory argument)
- New feature: if `path` is a .xlsx full path instead of a directory path, use that name for the `filename` argument.

**Comment by JulienBlasco** [comment]
Added a second suggestion

**Comment by JulienBlasco** [comment]
@ddotta is there a reason why `path` is not in second position already?

**Comment by ddotta** [comment]
No particular reason, you can move it to the second position
